name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"    # Runs every day at 00:00 UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: RabindraD234
          outputs: |
            ./github-snake-dark.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-snake-dark.svg
          git commit -m "chore: update GitHub Snake Animation"
          git push
